# Generated by Django 5.1.4 on 2024-12-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galvarinoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
