# Generated by Django 5.1.4 on 2024-12-18 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galvarinoApp', '0002_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepersonalizado',
            name='clave_usuario',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientepersonalizado',
            name='rol',
            field=models.CharField(choices=[('normal', 'Comprador'), ('picker', 'Picker'), ('administrador', 'Administrador')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientepersonalizado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
